version: '3'

services:
  server:
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    volumes:
      - ./server/src:/app/src
      - ./server/requirements.txt:/app/requirements.txt
